Repository experienced-dev/java-starter-template, pull requests merged in 2023-08, with the labels that each got.

#4 feat: add .gitignore Closes #2
  .gitignore
Labels: complexity-1, priority-3-medium

#16 Add MIT licence
  LICENSE
Labels: complexity-1, priority-3-medium

#13 Spring App
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  .gitignore
  Dockerfile
  README.md
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/java/experienced/dev/javastartertemplate/JavaStarterTemplateApplication.java
  src/main/java/experienced/dev/javastartertemplate/TemplateController.java
  src/main/resources/application.properties
  src/test/java/experienced/dev/javastartertemplate/JavaStarterTemplateApplicationTests.java
  src/test/java/experienced/dev/javastartertemplate/TemplateControllerTest.java
Labels: status:in-progress, priority-3-medium

#18 refactor: Dockerfile
  .dockerignore
  Dockerfile
  gradlew
Labels: complexity-1, priority-3-medium

#19 fix: typo in a swagger-ui path
  README.md
Labels: complexity-1, priority-3-medium

#24 Kaniko
  .github/workflows/build.yaml
Labels: status:ready, complexity-1, priority-2-high
